apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: limit-request-size
  # highlight-next-line
  namespace: prod # 选择指定 ingressgateway 所在的命名空间
spec:
  # highlight-start
  workloadSelector: # 选中指定 ingressgateway
    labels:
      app: istio-ingressgateway-public # 替换指定 ingressgateway 的 label
  # highlight-end
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: "envoy.filters.http.buffer"
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer"
            # highlight-next-line
            max_request_bytes: 1048576 # 1MB, 请求最大限制
