apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: limit-header-size
  # highlight-next-line
  namespace: prod # 选择指定 ingressgateway 所在的命名空间
spec:
  # highlight-start
  workloadSelector: # 选中指定 ingressgateway
    labels:
      app: istio-ingressgateway-public # 替换指定 ingressgateway 的 label
  # highlight-end
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            # highlight-next-line
            max_request_headers_kb: 96 # 96KB, 请求 header 最大限制
